### ISSUE TITLE
Any way to stop/cancel mapSlicer?

### ISSUE THREAD

**Issue by ilyaerkhov** [martinheidegger/mapslice#24]

**Comment by martinheidegger** [comment]
At the moment: no.

**Comment by martinheidegger** [comment]
In https://github.com/martinheidegger/mapslice/commit/98fb465a155455511f5dec1122ea17a2a61c58d0 I added support for stop/cancel by passing-in an abort signal much like in one would do in `fetch`. This is also automatically used in the cli by pressing `ctrl+c`.

Released on npm as v3.0.0 because some minor breaking changes happened in the refactoring: https://github.com/martinheidegger/mapslice/commit/1c80f13757152067452777782d13bd11c718e2cf
