### ISSUE TITLE
Image Cropping

### ISSUE THREAD

**Issue by ozcan-durak** [martinheidegger/mapslice#9]
Hi,

my actual image size : 4096 x 2048
I m trying to slice the image with tileSize : 512, 

in this case it should create "32" tiles. but instead creating 89 files with blank images. how can i prevent that.

**Comment by martinheidegger** [comment]
To make sure that applications don't return 404's mapslice creates full size square maps at the moment. so instead of 4096 x 2048 it thinks this map should be 4096 x 4096 and centers your image in there. This means it will create 8x8 (4096/512) = 64 tiles at its original size. Then it will scale it down in half: 2048 (4096/2) create 4x4 (2048/512) = 16 tiles at 50% scale factor. Then it will do that for 2x2 (1024/512) = 4 tiles at 25% scale factor and 1 tile at 12.5% scale factor. 64 + 16 + 4 + 1 = 85 files. Not quite sure how you get to 89 files (:smile: probably my mistake, have not touched it in a while). With those files you should be able to use a map viewer like that. If this is not what you want: I.e. you want to just tile one level then we  need to adopt this application. Can you give a suggestion how this should look like?

**Comment by ozcan-durak** [comment]
Hi thanks for the reply, Glad you calculated that :) 

Actualy i m trying to create a service to serve sliced image into pieces. I have 2 millions image which will be (4096x2048) and need to slice them by (512x512) into 32 pieces. In my case i dont need a zoom level. just need to tile them with cordinate. Is it possible create that with your library.

Regards

**Comment by martinheidegger** [comment]
It needs to be adopted. The technicality the features are there but it will need to be slightly rewritten (i.e.

**Comment by ozcan-durak** [comment]
i would be grateful if you can help with that.

**Comment by martinheidegger** [comment]
What sort of help do you need?

**Comment by ozcan-durak** [comment]
you said that the mapslice creates a fullsize square maps 4096x4096. is it possible to set that to 4096x2048 ?

**Comment by martinheidegger** [comment]
Well: that would be the former mentioned `ignoreEmpty` or lets call it `dropEmpty` where the tiles that "are 100% empty" would be deleted. Additionally you would need to specify a mode that specifies the required scale levels or zoom levels.

**Comment by martinheidegger** [comment]
Closing this issue, mapslice supports now `skipEmptyTiles`
